name: Bug Report
description: Report a bug in TowelWrap
title: "[Online Bug]: "
labels: ["Obug"]

body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug you encountered.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Tell us how to reproduce the bug.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
